### PR TITLE
I don't like flat files

### PR DESCRIPTION
**Pull request by stefanhayden**
now in a format some one can use.

### CODE REVIEW

**Comment by belden** [comment]
Could this PR be redone without deleting the flat files - and instead introducing a tool to build the .json file from the flatfiles? I worry that there are users of this project who are accustomed to the flat file format: they should be accommodated.

**Comment by patch** [comment]
See also PR #2 for discussion on this topic.

**Comment by stefanhayden** [comment]
no one likes flat files. Just pretend you are bootstrap or a new mac OS and call it BREAKING CHANGE. to the future!

**Comment by jacobbuck** [comment]
> no one likes flat files

:-1: That's a pretty subjective statement. Flat files are much more portable to use, and can be used by someone non-technical like a content publisher.

**Comment by lllama** [comment]
Just FYI, I found the flat files very useful for using with grep to filter badness out of a different list. +1 for a converter though.

**Comment by cesine** [comment]
@stefanhayden your wish is granted we made you a script and and a bower/npm package... https://github.com/LDNOOBW/naughty-words-js

**Pull request closed without merging**
