### PR TITLE
Update nl

### PR DESCRIPTION
**Pull request by UndiFineD**

### CODE REVIEW

**Comment by bobvdvelde** [comment]
These changes seem sensible, can this PR be merged?

**Comment by cesine** [comment]
Hi guys, can you tell us a bit more about these changes, I dont speak neerlandais. It looks like these are changes to the grammatical type of the words (removing `-g`?)

**Comment by UndiFineD** [comment]
yes mostly spelling corrections

**Comment by bobvdvelde** [comment]
It's not (just) grammatical type. Words such as `afgieteng` are simply incorrect (and not known slang either). It seems like the process of generating these words simply added `g` characters at random. These are errors that are immediately apparent to Dutch speakers and thus not very contentious. It's great that @UndiFineD made this PR to fix these pretty glaring errors. 

If you need verification on Dutch in the future, I'm also happy to help out.

**Pull request merged**
